# coding: utf-8

# flake8: noqa

from __future__ import absolute_import
import datetime
import json
import mimetypes
from multiprocessing.pool import ThreadPool
import os
import re
import tempfile
import six
from six.moves.urllib.parse import quote

from paapi5_python_sdk.configuration import Configuration
import paapi5_python_sdk.models
from paapi5_python_sdk import rest
from paapi5_python_sdk.auth.sign_helper import AWSV4Auth


class ApiClient(object):
    """Generic API client for Swagger client library builds.
    
    This client handles the client-server communication and is invariant across implementations.
    Specifics of the methods and models for each application are generated from the Swagger templates.

    NOTE: This class is auto generated by the swagger code generator program.
    Ref: https://github.com/swagger-api/swagger-codegen
    Do not edit the class manually.

    :param configuration: .Configuration object for this client
    :param header_name: a header to pass when making calls to the API.
    :param header_value: a header value to pass when making calls to the API.
    :param cookie: a cookie to include in the header when making calls to the API.
    """

    PRIMITIVE_TYPES = (float, bool, bytes, six.text_type) + six.integer_types
    NATIVE_TYPES_MAPPING = {
        'int': int,
        'long': int if six.PY3 else long,  # noqa: F821
        'float': float,
        'str': str,
        'bool': bool,
        'date': datetime.date,
        'datetime': datetime.datetime,
        'object': object,
    }

    def __init__(self,
                 access_key,
                 secret_key,
                 host,
                 region,
                 configuration=None,
                 header_name=None,
                 header_value=None,
                 cookie=None):
        if configuration is None:
            configuration = Configuration()
        self.configuration = configuration

        self.pool = ThreadPool()
        self.rest_client = rest.RESTClientObject(configuration)
        self.default_headers = {}
        if header_name is not None:
            self.default_headers[header_name] = header_value
        self.cookie = cookie
        # Set default User-Agent.
        self.user_agent = 'paapi5-python-sdk/1.0.0'

        self.access_key = access_key
        self.secret_key = secret_key
        self.host = host
        self.region = region

        # Ajouter des impressions pour vérifier les valeurs des paramètres
        print(f"[DEBUG] Initializing ApiClient with access_key: {access_key}, secret_key: {secret_key}, host: {host}, region: {region}")

    def __del__(self):
        self.pool.close()
        self.pool.join()

    @property
    def user_agent(self):
        """User agent for this API client"""
        return self.default_headers['User-Agent']

    @user_agent.setter
    def user_agent(self, value):
        self.default_headers['User-Agent'] = value

    def set_default_header(self, header_name, header_value):
        self.default_headers[header_name] = header_value

    def select_header_accept(self, accepts):
        """Returns `Accept` based on an array of accepts provided.
        
        :param accepts: List of headers.
        :return: Accept (e.g., application/json).
        """
        if not accepts:
            return

        accepts = [x.lower() for x in accepts]

        if 'application/json' in accepts:
            return 'application/json'
        else:
            return ', '.join(accepts)

    def select_header_content_type(self, content_types):
        """Returns `Content-Type` based on an array of content_types provided.
        
        :param content_types: List of content-types.
        :return: Content-Type (e.g., application/json).
        """
        if not content_types:
            return 'application/json'

        content_types = [x.lower() for x in content_types]

        if 'application/json' in content_types or '*/*' in content_types:
            return 'application/json'
        else:
            return content_types[0]

    def __call_api(
            self, resource_path, method, api_name, path_params=None,
            query_params=None, header_params=None, body=None, post_params=None,
            files=None, response_type=None, auth_settings=None,
            _return_http_data_only=None, collection_formats=None,
            _preload_content=True, _request_timeout=None):

        if self.access_key is None or self.secret_key is None:
            raise ValueError("Missing Credentials (Access Key and SecretKey). Please specify credentials.")

        print(f"[DEBUG] Calling API with access_key: {self.access_key}, secret_key: {self.secret_key}, host: {self.host}, resource_path: {resource_path}")

        config = self.configuration

        # header parameters
        header_params = header_params or {}
        header_params.update(self.default_headers)
        if self.cookie:
            header_params['Cookie'] = self.cookie
        if header_params:
            print(f"[DEBUG] Headers before serialization: {header_params}")
            header_params = self.sanitize_for_serialization(header_params)
            header_params = dict(self.parameters_to_tuples(header_params, collection_formats))
            print(f"[DEBUG] Headers after serialization: {header_params}")

        # path parameters
        if path_params:
            print(f"[DEBUG] Path params: {path_params}")
            path_params = self.sanitize_for_serialization(path_params)
            path_params = self.parameters_to_tuples(path_params, collection_formats)
            for k, v in path_params:
                resource_path = resource_path.replace(
                    '{%s}' % k,
                    quote(str(v), safe=config.safe_chars_for_path_param)
                )

        # query parameters
        if query_params:
            print(f"[DEBUG] Query params before serialization: {query_params}")
            query_params = self.sanitize_for_serialization(query_params)
            query_params = self.parameters_to_tuples(query_params, collection_formats)
            print(f"[DEBUG] Query params after serialization: {query_params}")

        # post parameters
        if post_params or files:
            print(f"[DEBUG] Post params or files before serialization: {post_params}")
            post_params = self.prepare_post_parameters(post_params, files)
            post_params = self.sanitize_for_serialization(post_params)
            post_params = self.parameters_to_tuples(post_params, collection_formats)
            print(f"[DEBUG] Post params or files after serialization: {post_params}")

        # auth setting
        print(f"[DEBUG] Headers before auth: {header_params}")
        self.update_params_for_auth(header_params, query_params, auth_settings, api_name, method, body, resource_path)
        print(f"[DEBUG] Headers after auth: {header_params}")

        # body
        if body:
            print(f"[DEBUG] Body before serialization: {body}")
            body = self.sanitize_for_serialization(body)
            print(f"[DEBUG] Body after serialization: {body}")

        # request url
        url = "https://" + self.host + resource_path
        print(f"[DEBUG] Request URL: {url}")

        # perform request and return response
        response_data = self.request(
            method, url, query_params=query_params, headers=header_params,
            post_params=post_params, body=body,
            _preload_content=_preload_content,
            _request_timeout=_request_timeout)

        print(f"[DEBUG] Response status: {response_data.status}")
        print(f"[DEBUG] Response headers: {response_data.getheaders()}")

        self.last_response = response_data

        return_data = response_data
        if _preload_content:
            # deserialize response data
            if response_type:
                return_data = self.deserialize(response_data, response_type)
            else:
                return_data = None

        if _return_http_data_only:
            return return_data
        else:
            return return_data, response_data.status, response_data.getheaders()
